[package]
name = "mockservice"
version = "1.3.1"
edition = "2024"
authors = ["Gregory Saliba", "gregtmj@gmail.com"]
description = "This project is meant to handle a mock service, that imitates responses from external services"
readme = "README.md"
repository = "https://github.com/GregTMJ/actix-web-example"
license-file = "LICENSE"
publish = false

[dependencies]
actix-web = "4.11.0"
tokio = {version = "1", features = ["full"] }
dotenv = "0.15"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "derive" ] }
serde = "1.0.219"
serde_json = "1.0.143"
log = "0.4"
env_logger = "0.11.8"

[dev-dependencies]
sqlx-cli = { version = "0.8.6", default-features = false, features = ["postgres"] }


[lints.rust]
unsafe_code = "forbid"

[[bin]]
path = "src/bin/main.rs"
name = "mockservice"

[profile.dev]
codegen-units = 16
incremental = true

[build]
jobs = 2
rustc-wrapper = "sccache"
rustc = "rustc"
